### ISSUE TITLE
dashboard's port 8080 is hard-coded in the TS code

### ISSUE THREAD

**Issue by abourget** [dfuse-io/dfuse-eosio#10]
We can now change the listening port for dashboard's grpc and http (like any other service), but the served up code defaults to `localhost:8080/api` when connecting back.

**Comment by elmato** [comment]
Also! https://github.com/dfuse-io/dfuse-eosio/blob/89581dc133a03278db574e19dd774643eca327cc/eosq/server.go#L114

**Comment by abourget** [comment]
these things are being shuffled around in latest `develop`.. have you pulled?

**Comment by abourget** [comment]
dashboard is now on `:8081`, and `eosq` +  all APIs on `:8080`, simpler.

**Comment by abourget** [comment]
Should solved now.
