### ISSUE TITLE
How to use existing nodeos and chain data

### ISSUE THREAD

**Issue by SpringBoom** [dfuse-io/dfuse-eosio#105]
I try config --mindreader-data-dir to existing chain data on my server. But the explorer show block 0.

**Comment by matthewdarwin** [comment]
You need to use the special dfuse version of nodeos to generate dfuse chain data.

**Comment by SpringBoom** [comment]
@matthewdarwin The nodes version is 1.8.3 and dfuse is 0.1.0-beat4 I'm using now. 
I'm trying to start the dfuseeos on my existing nodeos and data.It always sync from block 0. It will show current block when I curl /get_info.
Do you have any specific suggestions? thanks.

**Comment by sduchesneau** [comment]
follow this: https://docs.dfuse.io/eosio/admin-guide/installation/

then, with your other instance running accessible on the network, give its info when answering to `dfuseeos init` prompts.
If it's a large chain, you will need this: https://docs.dfuse.io/eosio/admin-guide/large-chains-preparation/
