### ISSUE TITLE
Allow mindreader to work without relayer (or clearly document it is required in minimal setup)

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#115]
When setting up a new environment, for an existing blockchain the first thing that needs to get going is mindreader to generate merged blocks. So really you just want to get this up and running and then investigate other "higher level" components later.

Since recent changes, mindreader now knows when to merge blocks by itself.  However, this knowledge depends on the relayer.  This may not be obvious to a new user that the minimal set of services that should be deployed is:

- mindreader (multiple)
- merger (single)
- blockmeta (multiple)
- relayer (multiple)

Code could be changed to allow this minimal configuration to run without the relayer.  Or make it clear in the documentation that relayer is required as part of the minimal configuration.

Of course once you get to a production situation, relayer is absolutely required.

**Comment by sduchesneau** [comment]
Clarification:

1) the mindreader can run without the blockmeta or relayer.
2) the optimization of mindreader creating merged files directly can work only based on '--mindreader-merge-threshold-block-age' -> setting this to 10 minutes will give good results (but become risky if the chain's LIB is not advancing steadily)
3) the optimization where mindreader will create merged files up to the current LIB (less risky then based on block age) does rely on additional information from the blockmeta (it's asking the blockmeta "what is the current LIB on the network", and the blockmeta is doing a query to its configured 'upstream nodeos API"

What needs to be done is to allow the blockmeta to start and serve some endpoints even if it does not have access to a stream yet (ex: no relayer..)
