### ISSUE TITLE
mindreader: finished unary call with code Unavailable (zap/server_interceptors.go:40)

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#126]
After starting mindreader, it generates a bunch of error messages:

```
finished unary call with code Unavailable (zap/server_interceptors.go:40)
```

Full log attached.

[mindreader.txt](https://github.com/dfuse-io/dfuse-eosio/files/5105405/mindreader.txt)

**Comment by matthewdarwin** [comment]
Seems to be the same issue as is resolved in https://github.com/dfuse-io/bstream/commit/dafb4c658b8895cb07424442e5aa46cdafe9e515

**Comment by sduchesneau** [comment]
The code that generates these calls (in relayer) has changed a lot since Aug. 20, I can't confirm the original cause, so feel free to reopen if it appears again!
