### ISSUE TITLE
Support versioning of filter expressions to allow for zero-downtime migrations

### ISSUE THREAD

**Issue by fproulx-dfuse** [dfuse-io/dfuse-eosio#129]
**Requirement:**
When the customer of a dedicated deployment requests to change the filter rules we need a way to allow for simplified zero-downtime migrations.

**Caveats:**
Currently, filtering rules are sanity checked by the consuming component as blocks flow. This leads to components panicking if they receive blocks with wrong filter.

**Proposed solution:**
- Assuming customer filter changes do not apply retroactively (inclusion or exclusion can be starting past a certain block (which is especially relevant for exclusion)
-  Given that the characters `;` and `@` are NOT allowed in neither `EOS` (as names), `CEL`, nor in `SQE`, we can use those as backwards-compatible, optional, delimiters in `--common-include-filter-expr` and `--common-exclude-filter-expr` flags.

**Examples:**

*No range specified (compatible with existing deployments (assumed to be range `[0, +∞)`):*
```
--common-exclude-filter-expr=account in ['scoin1','scoin2']
```

*Ranges specified:*
```
--common-exclude-filter-expr=0@account in ['scoin1','scoin2'];237000@account in ['scoin1','scoin2','scoin3']
```

**Comment by abourget** [comment]
I suggest we use this syntax instead:

```
--common-actions-include-filter-expr='account == "bob@bob"'
--common-actions-include-filter-expr='#12323;account == "bob"'
--common-actions-include-filter-expr='#12343323;account == "bob"'
--common-actions-include-filter-expr='#534312323; account == "bob"'
```

* This way, we keep the syntax simple for the simple case (when you pass only one filter), you have the option to add more as you go, cleanly as separate flags.
* The `#number;` syntax is slightly better because it starts with a character that is invalid in CEL, and we can easily regexp the flag without parsing the AST after a `;`.  If it's not present, it's assumed to be 0.

**Comment by sduchesneau** [comment]
problems with this syntax:
1) cobra will think "auth.exists(x, x =='blah')" is two values because of the comma
2) even if we fix this and `,` becomes normal, ppl won't be able to configure this flag using env variables

solution: do not make the flag repeatable and use `;;;` as the separator.
