### ISSUE TITLE
trxdb-loader healthz does not work as expected

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#137]
trxdb-loader is a bit weird.  When doing a `curl http://localhost:8080/healthz` returns **ready** as it should.  However, using telnet to connect closes the connection immediately even before providing the URL to query.

![image](https://user-images.githubusercontent.com/26171839/91922100-184ce500-ec9b-11ea-9c7b-1872888103ef.png)

**Comment by sduchesneau** [comment]
fixed!
```commit f64a6caeb8fa7a47d43ba6218d912a332efddf00 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Stéphane Duchesneau <stephane.duchesneau@eoscanada.com>
Date:   Wed Sep 2 11:01:48 2020 -0400

    remove aggressive readtimeout of 10ms on trxdb-loader healthcheck
```
