### ISSUE TITLE
Feature: allow merger to read from multiple one-block locations

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#140]
It appears (but is not proven), than in our environment when the s3 storage server is under extreme load, that one-block files go missing. The working theory is that having multiple deep-mind processes writing to the same file to the same location causes some race condition and the file just disappears.

Possible workaround: have each of the mindreaders write to its own location and then have the merger read from all those locations.

**Comment by sduchesneau** [comment]
work is on the way: https://github.com/dfuse-io/merger/pull/3

doing some tests, awaiting for for PR review, then it should be good to go!

**Comment by sduchesneau** [comment]
This branch https://github.com/dfuse-io/dfuse-eosio/tree/feature/dedupe-suffixed-oneblockfiles contains the feature. 
Works locally.
Mindreader needs new flag `--mindreader-oneblock-suffix` with its specific suffix, different from the other mindreaders.
