### ISSUE TITLE
error: could not get LIB from blockmeta after a few attempts  ,on https://github.com/dfuse-io/eos/tree/v2.0.6-dm-12.0

### ISSUE THREAD

**Issue by axisdefi** [dfuse-io/dfuse-eosio#151]
Error msg:

could not get LIB from blockmeta after a few attempts. Not merging blocks (mindreader/archiver_selector.go:106) {"error": "tracking fetch errors in order: tracker block not found"}

dfuse was  latest dev.

new to dfuse,  anybody can help resolve this error? 

thanks ahead.

**Comment by sduchesneau** [comment]
It is a warning level message not error level, it just means that the blockmeta is not (yet ? ) available, so the mindreader switches to its default behavior. Not an issue.

**Comment by axisdefi** [comment]
thanks for reply ,  as I am new to dfuse,   I follow whole tutorial , able to build and run.   

the dashboard show up well, as I can see current block number.

![image](https://user-images.githubusercontent.com/69355158/92958543-664eaf00-f438-11ea-9b63-eeddb900a896.png)

but the eosq just empty.

![image](https://user-images.githubusercontent.com/69355158/92958620-87170480-f438-11ea-91a9-bdfdbd25a19e.png)

any hint how to fix this?  

I almost go through all docs, but find no clue yet.

**Comment by maoueh** [comment]
How eosq is being accessed? Remotely?

**Comment by axisdefi** [comment]
everything is local
