### ISSUE TITLE
Nodeos config issue on exposing REST port on Docker windows

### ISSUE THREAD

**Issue by mmcs85** [dfuse-io/dfuse-eosio#16]
There's an issue on nodeos on exposing REST port on Docker windows that needs the IP changed from 127.0.0.1 -> 0.0.0.0

https://github.com/dfuse-io/dfuse-eosio/blob/develop/launcher/cli/config.ini.go#L48
http-server-address = 127.0.0.1:8888
To
http-server-address = 0.0.0.0:8888

**Comment by abourget** [comment]
This is generated local config. We've changed the way dfuse generates those `config.ini` and allow you to more easily tweak them.

Do you think it's preferable to have `0.0.0.0` as a default?  We wanted to keep the default more secure, and let you open it as needed.

**Comment by mmcs85** [comment]
I understand, makes sense to make it default in the local network. I can "sed" the config after the dfuse.yaml is generated to change it for what I need.

**Comment by abourget** [comment]
We're about to release a new `dfuseeos` which will make all chose `config.ini` readily available in the current directory... and only scaffold once.. and also not be intertwined in a .yaml file.

Thanks for pitching in !

**Comment by mmcs85** [comment]
sure that would make it better. I have created a docker build with dfuse now with all the correct ports exposed. so is looking great!
