### ISSUE TITLE
Token Symbol in Account & (some)Transaction Details

### ISSUE THREAD

**Issue by basarrcan** [dfuse-io/dfuse-eosio#181]
1. As ORE Chain we have 2 different tokens under eosio.token contract that is being used for resource allocation purposes. SYS and ORE. We created a high-level staking logic a predefined tier system, allowing users to only use ORE tokens to interact with system actions, hiding the acutal use of SYS for buyram / delegatebw on background. Thus ORE is the practical system token in our chain. We want to show ORE balance in the balance section of account details page.

2. In transaction details, some actions show hard-coded token symbol as EOS (e.g. claimrewards) we want all hard-coded EOS symbols change to ORE.

**Comment by basarrcan** [comment]
3. We also want to change the Chain name that is written on the upper right side of the page. Currently, it is Aikon ORE. Can we make it Open Right Exchange (ORE)

**Comment by maoueh** [comment]
All fixed.
