### ISSUE TITLE
Error propagation should encapsulate with the name of the culprit

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#187]
See https://github.com/dfuse-io/dfuse-eosio/issues/186.

When search-forkresolver has an error, it propogates the error upstream to abicodec (for example).  abicodec writes out this error message but it is not clear that the error comes from search-forkresolver .... from the logs it looks like the error is from itself.

**Comment by sduchesneau** [comment]
I just modified the wording, the log should now look as such:

```"streamABIChanges interrupted", "error": "received the following error from the search service: rpc error: code = Unknown desc = error running fork resolver: rpc error: code = Unknown desc = opening ramdisk-based scorch index: mkdir {dfuse-data-dir}: permission denied"```

I don't see a more generic way of addressing this, I believe all the information was there, only lacked clarification that the error was "received from the search service".

Is that clearer to you ?

**Comment by matthewdarwin** [comment]
Sounds fine.
