### ISSUE TITLE
abi-cache.json.zst: no such file or directory

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#198]
`{"level":"info","ts":1610959067.8308263,"logger":"tokenmeta","caller":"tokenmeta/app.go:206","msg":"abi cache file is not available, retrying...","error":"open /home/dfuseeos/dfuse-data/storage/abicache/abi-cache.json.zst: no such file or directory"}
`
After running dfuseeos, dfuse.log.json shows a log that the `abi-cache.json.zst` file cannot be found. Check that the file does not exist in the corresponding directory. How to create or obtain the file?

**Comment by sduchesneau** [comment]
the abi-cache.json file will be produced from the abicodec once it starts syncing up the chain and sees the first "setabi" action on the chain. Your other components (fully produced dfuse blocks files, trxdb and statedb) need to be in sync.  Please read this for syncing dfuse with an existing chain.
https://docs.dfuse.io/eosio/admin-guide/large-chains-preparation/

**Comment by cppfuns** [comment]
https://github.com/dfuse-io/dfuse-eosio/issues/200

At present, it seems to be related to this problem, and there is no such problem in the test chain of dfuseeos initialization
