### ISSUE TITLE
shutting down on relayer error, because drift exceeded tolerated maximum

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#201]
When running for one night, the node program exited, prompting the following error
```
################################################################
Fatal error in app relayer:

shutting down on relayer error, because drift exceeded tolerated maximum: current_drift: 300859319571
################################################################
 (launcher/launcher.go:174) 
Application relayer shutdown unexpectedly, quitting 
Error: unable to launch: shutting down on relayer error, because drift exceeded tolerated maximum: current_drift: 300859319571
dfuse (derr/cli.go:25) {"error": "unable to launch: shutting down on relayer error, because drift exceeded tolerated maximum: current_drift: 300859319571"}
dgraphql terminated with error (dgraphql/server.go:83) {"error": "shutting down on relayer error, because drift exceeded tolerated maximum: current_drift: 300859319571"}
search forkresolver terminated with error (forkresolver/forkresolver.go:117) {"error": "shutting down on relayer error, because drift exceeded tolerated maximum: current_drift: 300859319571"}
router terminated with error (router/router.go:225) {"error": "shutting down on relayer error, because drift exceeded tolerated maximum: current_drift: 300859319571"}

```

**Comment by maoueh** [comment]
This errors occurs when the relayer connects to a mindreader and the mindreader is not fully synced yet, i.e. it’s not real time and still catching up with the node.

A /v1/chain/get_info on mindreader Nodeos RPC api should give a hint about if it caught up with real-time blocks. The default port is 8888 if I recall right, check the value defined in mindreader/config.ini.

It’s possible to configure it so does not stop like this by tweaking the max drift flag (`dfuseeos start —help | grep relayer` to list app specific flags)

**Comment by cppfuns** [comment]
```
surou@ubuntu:~/Documents$ ./dfuseeos start —help | grep relayer
Error: unable to launch: cannot launch un-registered application "—help"

```

**Comment by maoueh** [comment]
Sorry I was on my phone and it converted `--` to `—`, `dfuseeos start --help | grep relayer` is the right command.

Is this related to your other issue? I would close this one and concentrate on the other one, I think everything is "together"

**Comment by cppfuns** [comment]
```
./dfuseeos start --help | grep relayer
  dfuseeos start relayer merger --merger-grpc-serving-addr=localhost:12345 --relayer-merger-addr=localhost:12345
  relayer
      --common-blocks-store-url string                         [COMMON] Store URL (with prefix) where to read/write. Used by: relayer, statedb, trxdb-loader, blockmeta, search-indexer, search-live, search-forkresolver, eosws (default "file://{dfuse-data-dir}/storage/merged-blocks")
      --common-blockstream-addr string                         gRPC endpoint to get real-time blocks. Used by: statedb, trxdb-loader, blockmeta, search-indexer, search-live, eosws (relayer uses its own --relayer-blockstream-addr) (default ":13011")
      --relayer-buffer-size int                                number of blocks that will be kept and sent immediately on connection (default 300)
      --relayer-grpc-listen-addr string                        Address to listen for incoming gRPC requests (default ":13011")
      --relayer-init-time duration                             time before we start looking for max drift (default 1m0s)
      --relayer-max-drift duration                             max delay between live blocks before we die in hope of a better world (default 5m0s)
      --relayer-max-source-latency duration                    max latency tolerated to connect to a source (default 1m0s)
      --relayer-merger-addr string                             Address for grpc merger service (default ":13012")
      --relayer-min-start-offset uint                          number of blocks before HEAD where we want to start for faster buffer filling (missing blocks come from files/merger) (default 120)
      --relayer-source strings                                 List of Blockstream sources (mindreaders) to connect to for live block feeds (repeat flag as needed) (default [:13010])

```

This is encountered when running the initial chain environment provided by dfuseeos. Dashboard does not warnning in this environment(https://github.com/dfuse-io/dfuse-eosio/issues/200), but it will exit because of this error. I think this is not related to the previous problem, so I submitted a separate one.

**Comment by cppfuns** [comment]
Do I need to extend the relay-max-drift time? But I see that this setting has been removed

https://github.com/dfuse-io/dfuse-eosio/blob/448bbbb85fcad467e0561f5d926ee9d7acdc5fde/CHANGELOG.md#removed

`Removed relayer-max-drift (now dependent on a new condition of presence of a "block hole", and no new block sent for 5 seconds)`

**Comment by maoueh** [comment]
> This is encountered when running the initial chain environment provided by dfuseeos

Ok, so I could reproduce roughly with those steps if I get it right:

```
cd /tmp/testing
dfuseeos init # Answers y to start block producer for me
dfuseeos start
# Wait overnight to see if relayer stops the whole thing
```

Is that correct?

If blocks are produced correctly and nothing stop the `dfuseeos start` process, this should not happen. Maybe the trigger is not tolerant enough.

**Comment by cppfuns** [comment]
> > This is encountered when running the initial chain environment provided by dfuseeos
> 
> Ok, so I could reproduce roughly with those steps if I get it right:
> 
> ```
> cd /tmp/testing
> dfuseeos init # Answers y to start block producer for me
> dfuseeos start
> # Wait overnight to see if relayer stops the whole thing
> ```
> 
> Is that correct?
> 
> If blocks are produced correctly and nothing stop the `dfuseeos start` process, this should not happen. Maybe the trigger is not tolerant enough.

Yes, for this problem, I am so easy to operate. I have the same problem when I run it overnight on local and cloud servers (8 cores, 16GB).

**Comment by maoueh** [comment]
I’ll start one tonight and let it run overnight.

In the mean time, do you have the logs of such run?

**Comment by cppfuns** [comment]
Due to github upload file type restrictions, you need to rename dfuse.log.json.7z.log to dfuse.log.json.7z, and then use 7z to decompress

[dfuse.log.json.7z.log](https://github.com/dfuse-io/dfuse-eosio/files/5853160/dfuse.log.json.7z.log)

**Comment by cppfuns** [comment]
I have discovered the SEARCH ROUTER in this dashboard, its head block does not grow for a long time
I don’t know if this will cause the problem in this discussion
![image](https://user-images.githubusercontent.com/7980920/105441396-72c6fc00-5ca3-11eb-855b-bfe22f2a5630.png)
@maoueh

**Comment by cppfuns** [comment]
Is the tracker-miner-f process related to dfuseeos? Is it necessary to run?

![image](https://user-images.githubusercontent.com/7980920/105470107-1b8d4f80-5cd4-11eb-82d4-ad6d6a59748d.png)

**Comment by cppfuns** [comment]
![image](https://user-images.githubusercontent.com/7980920/105484932-171e6200-5ce7-11eb-9e26-61d7a34e7bac.png)

**Comment by maoueh** [comment]
I was not able to reproduce the error, I run the instance over night on my laptop, produced 70K blocks without any problem. The search router head block is irrelevant also, it's a UI thing that should not be displayed for this app.

> Is the tracker-miner-f process related to dfuseeos? Is it necessary to run?

I don't have any idea what this is. Never seen it. 

Here what Google finds: https://www.reddit.com/r/SolusProject/comments/atckw3/what_exactly_is_trackerminerfs_as_shown_under/

Since this process has so high CPU, and seems to be related to some indexing functionality, it's probably trying to index some of the massive files generated by dfuseeos and it clogs everything to a point where no blocks is received by the `relayer` within the allowed time.

**Comment by cppfuns** [comment]
I ran for another night last night, and this error still occurs. I always use the default configuration. I still feel that something is not right. I will try again.

![image](https://user-images.githubusercontent.com/7980920/105565511-22fb3a00-5d62-11eb-8cae-5f634e9ccfc5.png)

**Comment by cppfuns** [comment]
@maoueh

**Comment by cppfuns** [comment]
Probably the conditions for recurring the problem have been measured. If the number of blocks in the running chain is larger, the synchronization node (v2.0.8-dm.12.0) running by dfuseeos needs to catch up with enough blocks (about 70- 80 w block), because the component processing block in dfuseeos is slower than the synchronization block, so too much data will accumulate, and "shutting down on relayer error, because drift exceeded tolerated maximum" will appear. If you redeploy the test chain, then dfuseeos will run as soon as possible, that is, make the block count difference small enough to run stably. In this case, how to make dfuseeos run synchronously from scratch when there are enough blocks in the existing chain?

**Comment by cppfuns** [comment]
At present, this problem needs to be followed up, and dfuseeos is initialized based on the existing chain, and running eosws using the default generated dfuse.yaml will report WARNING and need to modify dfuse.yaml
```
  flags: 
    apiproxy-nodeos-http-addr: :9888
    blockmeta-eos-api-upstream-addr: :9888
    eosws-nodeos-rpc-addr: :9888
```

**Comment by maoueh** [comment]
I will concentrate on the last "segment" of the logs you provided between 03:35 and 04:01. Those are EST timezone.

The logs attached to this issue seems to contain multiple runs, if possible, try to clean the logs upon restart.

```
03:35 The trace starts at that time
03:35 Mindreader starts, seems to start around block ~73K
03:35 Relayer starts
03:35 Mindreader produce merged blocks (blocks are >12h)
03:35 Relayer latency with source is too high
03:37 Mindreader is now producing one blocks
04:01 Mindreader catch up with live chain
04:01:10 Mindreader received blocks are live (latency <100ms)
04:01:14 Relayer latency is low enough to try to create blocks stream
04:01:44 Merger is currently merging blocks #135000 (there is probably 100 000+ one blocks waiting to be merged here)
04:02:11 Relayer is looking for merged blocks file 208600 (which is probably not written yet by merger)
04:02:15 Relayer is now monitoring drift (`now monitoring drift {"logger":"relayer","max_drift":300}`)
04:02:15 Mindreader last received blocks (binary is stopped by relayer at that point)
04:02:15 Relayer app is stopped, everything goes down
```

This occurs because "live" blocks are available but but the merger is too slow on your environment to catch up quickly with the amount of one blocks to merge. The average I see in the logs is like ~9s, this is a bit long to merge 100 blocks files together, I assume this is because of slow disk or too much disk activity. It will eventually catch up, will just take time since new blocks are also produced while the merging tries to catch up.

Now, the max drift logic has been removed in the `develop` branch of dfuse for EOSIO repository. The new logic is better and should not exist anymore. You will need to build from source however. I can provide a compiled binary if you would like to try or struggles with building from source.

I was under under the impression that it was already the case in your version, but it's not. You can also set the config value `relayer-max-drift: 0` in your current version which will prevent the relayer from completely stop due to drift being too high. This flag has been removed and will not available anymore, so upgrading might be a better path forward.

For larger chain, few millions block, maybe even less for chain with higher traffic, our recommendation is to perform the "live" part and the historical parts separately, a mindreader starts from a snapshot very close to the live block with a merger and a relayer so that the live blocks are up. At the same time, another mindreader (or multiple ones at various height) are also started to fill the historical blocks.

**Comment by cppfuns** [comment]
After compiling with the latest code, this problem does not exist when running
