### ISSUE TITLE
How to configure apiKey in dfuse-eosio that I built and run by myself

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#206]
How to configure apiKey in dfuse-eosio that I built and run by myself
When createDfuseClient is executed, two parameters need to be configured. I checked the code and saw three related parameters 
- eosq-auth-url 
- eosq-http-listen-addr 
- eosq-api-key, 

how do I need to set them

https://github.com/dfuse-io/docs/blob/16065f8d4da36aa32d66f43060822f287be8763f/quickstarts/javascript/node/index.eosio.js#L7

**Comment by cppfuns** [comment]
@maoueh need help

**Comment by maoueh** [comment]
The open source version we ship has no authentication mechanism built-it, it has an authentication plugin system where a user implementation can be provided, requires Golang coding of that module. Or by protected by some other means at the network level.

The client-js has an example how to configure the client for dfuse for EOSIO instances: https://github.com/dfuse-io/client-js/blob/master/examples/basic/dfuse-for-eosio.ts
