### ISSUE TITLE
How to make the dashboard accessible from the Internet?

### ISSUE THREAD

**Issue by cppfuns** [dfuse-io/dfuse-eosio#208]
How to make the dashboard accessible from the Internet? I tried the parameters, but no success. Can this dashboard be accessed from the Internet?

https://github.com/dfuse-io/dfuse-eosio/blob/515bb82773ff05e5f13c74914b0ef71197b795bd/cmd/dfuseeos/cli/dashboard.go#L19

![image](https://user-images.githubusercontent.com/7980920/105968624-473c7b00-60c2-11eb-8800-efbbd8955cbb.png)

**Comment by maoueh** [comment]
Foremost, we do not recommend exposing the dashboard to the internet. 

There is no option like eosq to change which endpoint the webapp reaches. To expose it to the internet, a rebuild is required of the dashboard client React application with the `REACT_APP_DASHBOARD_GRPC_WEB_URL` set to the public URL to reach.

It's essentially following the build from source steps but setting `REACT_APP_DASHBOARD_GRPC_WEB_URL=https://...` before calling the `yarn build` command used to build the dashboard.

**Comment by cppfuns** [comment]
If possible, it is recommended to support parameterization. Because the default is the local address, there is no UI interface for the server version of the server. I will compile a copy of it first according to the answer you gave.

**Comment by cppfuns** [comment]
I modified the `dlauncher\dashboard\client\src\.env` REACT_APP_DASHBOARD_GRPC_WEB_URL in this file to my external network address, but the program still accesses the local address

**Comment by maoueh** [comment]
I'm not sure why this `.env` file exists in fact, it's probably a leftover from previous version.

I used `REACT_APP_DASHBOARD_GRPC_WEB_URL="https://mytest-eosio.com" yarn build` and I can validate that the URL is changed in the static built files.
