### ISSUE TITLE
Add grpc health for publicly facing services

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#220]
Add grpc health for publicly facing services

```
grpc_health_probe -addr eos.dfuse.eosnation.io:9000 -tls
error: this server does not implement the grpc health protocol (grpc.health.v1.Health)
```

**Comment by maoueh** [comment]
This is for Firehose correct?

I thought I had implemented it through gRPC as well as HTTP, I will double check when I have some spare time.

**Comment by matthewdarwin** [comment]
Firehose grpc health check works fine.  This is for "regular dfuse".

**Comment by sduchesneau** [comment]
That "regular dfuse" is actually dgraphql. 
That service does not have a live stream directly hooked in it, so readiness is only based on whether or not:
1) the grpc server is started
2) it is not in the process of shutting down (ctrl-c called and we are within --common-system-shutdown-signal-delay)

It's been included.
```
commit 1e39ae64246fae14100b98acf3cef498aa88c2c4 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Stéphane Duchesneau <stephane.duchesneau@eoscanada.com>
Date:   Mon Apr 12 16:09:20 2021 -0400

    bump dgraphql, now serves simple GRPC Health service
```
