### ISSUE TITLE
mindreader doesn't always exit cleanly when on shutdown request

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#221]
I have seen this error a few times now.  dfuse has a fatal error during the shutdown sequence and then doesn't exit cleanly and corrupts the nodeos state.  Any ideas?

 2021-04-06T17:26:14.793Z (mindreader-stdin) failed storing block in archiver, shutting down and losing blocks in transit... (mindreader/mindreader.go:265){"error": "open file: open /var/lib/dfuse/mindreader/work/0083781/0083781411-20210406T172615.0-3f3cff36-93b38eda-dom12.dat.temp: permission denied"}

after this mindreader exits before consuming all the messages from nodeos and then nodeos state ends up being corrupt.

**Comment by sduchesneau** [comment]
Fixed here:

https://github.com/dfuse-io/dfuse-eosio/commit/88cac5516b5515fa966770a43a9a87baa0e95f63

bumped this:

https://github.com/dfuse-io/node-manager/commit/b4fd774f4cb1805aeaf26c36aa948ce9d5aaee7d (this is a fix/branch, that fix is also cherry-picked in develop)

New behavior correctly drains all the blocks from nodeos and discards them if it can't write to disk. This will also result in a "hole" in the blocks, but at least won't corrupt your nodeos.
