### ISSUE TITLE
dfuse patch on eosio 1.6.x dm cannot compile

### ISSUE THREAD

**Issue by JasonPan2008** [dfuse-io/dfuse-eosio#222]
https://github.com/dfuse-io/eos/tree/release/1.6.x-dm

**Comment by matthewdarwin** [comment]
eosio 1.6 is very old.  current is 2.0

**Comment by maoueh** [comment]
@JasonPan2008 We officially support only 2.0.x currently. The old patches, even on 1.8.x do not include latest features and most probably event if they compile, wouldn't work.

From a 1.8 chain, you can definitely sync using 2.0 without requiring to upgrade the BPs. On 1.6, I assume it would work also when syncing with a 2.0 nodeos.

The patch is required only to extract information from the chain, so syncing on the same network with a 2.0 is a correct use case.

Tell us how it goes, don't hesitate to get in touch with our team over Telegram or Email if you have specific business requirements.

I'm closing this.
