### ISSUE TITLE
'tokens' query: incorrect value for totalSupply 

### ISSUE THREAD

**Issue by YaroShkvorets** [dfuse-io/dfuse-eosio#228]
As far as I understand, `totalSupply` should represent current circulating supply. Instead, it seems to be equal to `maximumSupply`. 

See sample query: [GraphQL link](https://eos.dfuse.eosnation.io/graphiql/?query=cXVlcnkgKCR0b2tlblN5bWJvbHM6IFtTdHJpbmchXSwgJHRva2VuQ29udHJhY3RzOltTdHJpbmchXSkKewogIHRva2Vucyh0b2tlblN5bWJvbHM6ICR0b2tlblN5bWJvbHMsIHRva2VuQ29udHJhY3RzOiAkdG9rZW5Db250cmFjdHMpIHsKICAgIGVkZ2VzIHsKICAgICAgY3Vyc29yCiAgICAgIG5vZGUgewogICAgICAgIHN5bWJvbAogICAgICAgIGNvbnRyYWN0CiAgICAgICAgaG9sZGVycwogICAgICAgIHRvdGFsU3VwcGx5CiAgICAgICAgbWF4aW11bVN1cHBseQogICAgICB9CiAgICB9CiAgfQp9&variables=ewogICJ0b2tlblN5bWJvbHMiOiBbIlVTRFQiXSwKICAidG9rZW5Db250cmFjdHMiOlsidGV0aGVydGV0aGVyIl0KfQ==)

**Comment by maoueh** [comment]
I've asked Matthew Darwin from EOS Nation to deploy the fixed version
