### ISSUE TITLE
`accountBalances` query: wrong balance with "EOS_INCLUDE_STAKED" option enabled

### ISSUE THREAD

**Issue by YaroShkvorets** [dfuse-io/dfuse-eosio#238]
Returning balance seems to be off: [GraphiQL query](https://eos.dfuse.eosnation.io/graphiql/?query=cXVlcnkoJGFjY291bnQ6IFN0cmluZyEsICRsaW1pdDogVWludDMyLCAkdG9rZW5Db250cmFjdHM6IFtTdHJpbmchXSwgJG9wdHM6IFtBQ0NPVU5UX0JBTEFOQ0VfT1BUSU9OIV0pIHsKICBhY2NvdW50QmFsYW5jZXMoYWNjb3VudDogJGFjY291bnQsbGltaXQ6ICRsaW1pdCwgdG9rZW5Db250cmFjdHM6JHRva2VuQ29udHJhY3RzLCBvcHRpb25zOiAkb3B0cykgewogICAgYmxvY2tSZWYgewogICAgICBpZAogICAgICBudW1iZXIKICAgIH0KICAgIGVkZ2VzIHsKICAgICAgbm9kZSB7CiAgICAgICAgYWNjb3VudAogICAgICAgIGNvbnRyYWN0CiAgICAgICAgc3ltYm9sCiAgICAgICAgcHJlY2lzaW9uCiAgICAgICAgYmFsYW5jZQogICAgICB9CiAgICB9CiAgfQp9&variables=ewogICJhY2NvdW50IjogImIxIiwKICAidG9rZW5Db250cmFjdHMiOlsiZW9zaW8udG9rZW4iXSwKICAib3B0cyI6IFsKICAgICJFT1NfSU5DTFVERV9TVEFLRUQiCiAgXSwKICAibGltaXQiOiAxMAp9)

Returns **87283740.0148 EOS** balance, while in reality account has **76081745.0199 EOS** (liquid + staked)

**Comment by matthewdarwin** [comment]
Now it shows "balance": "76083745.0211 EOS"

So I think it is ok.

**Comment by YaroShkvorets** [comment]
Yep, looks like rebuilding StateDB fixed it. Closing.
