### ISSUE TITLE
nodeos console log truncation

### ISSUE THREAD

**Issue by swatanabe** [dfuse-io/dfuse-eosio#251]
The changes to nodeos to support dfuse include a change to make stdout unbuffered (https://github.com/EOSIO/fc/pull/148#discussion_r393092503).

It should not be necessary to make stdout unbuffered in order to prevent truncation, unless the standard library is buggy.

In fact, it appears that the truncation is not actually happening in nodeos at all, but rather on the reader side.  The library used to manage the nodeos subprocess and pipes (https://github.com/ShinyTrinkets/overseer) can truncate lines longer than 16384 bytes (https://github.com/ShinyTrinkets/overseer/blob/master/cmd.go#L602) under some circumstances (the limit can be adjusted per stream via SetLineBufferSize).  If nodeos' stdout is buffered, large lines will be split across multiple writes, which triggers this truncation.  On the other hand, making stdout unbuffered causes the log record to be written in a single `write` call, which bypasses this truncation.

This workaround is really fragile.  It would be much better to makes sure that the the console reader can handle long lines consistently.

**Comment by maoueh** [comment]
We use a fork of Overseer where the default value for the line buffer can be changed, which we do here: [DEFAULT_LINE_BUFFER_SIZE change](https://github.com/dfuse-io/dfuse-eosio/blob/b5940c1411a4569d56bded37d3d4764ab59a2c4c/node-manager/superviser/superviser.go#L127).

We always had override to read long lines because it bitten us rapidly. 

> If nodeos' stdout is buffered, large lines will be split across multiple writes, which triggers this truncation

Now from memory,  the main problem with buffered output is the inability to make any correct error handling which prevented us from detecting that the line are truncated. Using buffered output made the error handling robust at least to ensure that everything was written correctly. 

>  On the other hand, making stdout unbuffered causes the log record to be written in a single write call, which bypasses this truncation.

What problem is it causing exactly to have it like expect that long lines are kept in memory somewhere until the line is written using a single `write` call?

> This workaround is really fragile. It would be much better to makes sure that the the console reader can handle long lines consistently.

What kind of fragility are we talking about here exactly? This has been running for 2 years and more which being a problem as far as I know.

**Comment by swatanabe** [comment]
Clearly I was wrong about overseer, then.  However, there's definitely something fishy about the unbuffered output fixing the truncation.  The standard library itself has error handling for partial writes, and this handling is basically the same as yours.  I'll do some more digging.

**Comment by swatanabe** [comment]
By fragile, I mean that it could be broken by changes in the kernel or the go implementation.

**Comment by swatanabe** [comment]
> What problem is it causing exactly to have it like expect that long lines are kept in memory somewhere until the line is written using a single `write` call?

The problem is the assumption that a single write is read by a single read.  Neither posix nor go make any such guarantee.

**Comment by maoueh** [comment]
> Clearly I was wrong about overseer, then. However, there's definitely something fishy about the unbuffered output fixing the truncation. The standard library itself has error handling for partial writes, and this handling is basically the same as yours. I'll do some more digging.

I don't think it actually fixed the truncation issue, at least not directly. It probably made it easier to detect and retry the write fully, but I'm pretty sure that even at that time, we never had in mind that switching to unbuffered was fixing the truncation issue but more that it was making the whole system more robust.

Or motivation was let's have some "atomicity" and control. 

> The problem is the assumption that a single write is read by a single read. Neither posix nor go make any such guarantee.

I don't think there is such assertion that it must be read in one syscall nor that we expect that. There is no problem if multiple read syscall are performed, as long as the total "read" call makes a full line at some point (i.e. a line ending with a `\n`) and this line makes it to the line buffer underlying array.

The retry code in `dmlog_appender.cpp` could also result in multi `write` call which could be read in 1 or N read calls. As long as we reconstruct a full line, we know it was fully written from the other side.

**Comment by swatanabe** [comment]
The underlying issue is probably that the `write` can be interrupted by a signal handler.  `stdio` in `glibc` does not handle `EINTR`.  I was really surprised to find this, given that it seems like a pretty serious issue and it's not hard to do.  Related: https://stackoverflow.com/questions/56414520/fgets-signals-eintr-and-input-data-integrity.  nodeos has two relevant signal handlers: SIGINT, SIGTERM, SIGPIPE, and SIGHUP are handled in appbase via asio.  There is also a timer in platform_timer_posix.cpp which uses SIGRTMIN.  Neither of these sets SA_RESTART which would automatically resume the `write` and avoid this problem.

I'm going to try to confirm this hypothesis.  If it really is correct, then the problem may extend to other I/O in nodeos as well.

**Comment by swatanabe** [comment]
Okay, I've confirmed that signals can cause this problem.  I'm fixing up the signal handling in mandel to prevent it.  Do you happen to know whether any errors other than EINTR ever appear?  The message for EINTR would be something like "Interrupted system call."

**Comment by maoueh** [comment]
> Interrupted system call.

Seems to recall it was that but we hit that like 2 years ago, so my memory as fainted a little bit since then.

**Comment by swatanabe** [comment]
The current version reports when there's a truncated write, right?  The only other error that I've seen in my testing is EPIPE, which is caused by my test harness and is unrecoverable.  Anyway, I'm now confident that I understand the issue, and it isn't a problem in this repo, so I'm closing this issue.

**Comment by maoueh** [comment]
It does report the truncation only if we are unable after 5 tries to fully write the line.

**Comment by swatanabe** [comment]
The code here prints on every retry: https://github.com/EOSIO/fc/blob/eosio-2.2.x/src/log/dmlog_appender.cpp#L55, unless I'm really misreading it.  Is the version you're using different?

**Comment by maoueh** [comment]
Yes but it prints to `stderr` for logging purposes, I just meant that it's not an error for the "protocol" view just yet.
