### ISSUE TITLE
Syncing mindreader with 'merge-and-upload-directly' creates a hole in continuity when it restarts

### ISSUE THREAD

**Issue by maoueh** [dfuse-io/dfuse-eosio#30]
While doing phase 1 of chain sync, we use the `mindreader-merge-and-upload-directly` which means each time `mindreader` restarts, it must go back a little in time, to ensure there is no missing merge blocks bundle created.

This however is problematic until the first snapshot is taken. In this case, since there is no snapshot, `mindreader` will simply restart using the actual `blocks.log/state` file of `nodeos` which will create a hole in the "merged bundles". This is usually a problem only if hitting `Ctrl-C`. If the process is still running but `nodeos` restarts, I **think** (but not 100% sure) that information is kept in dfuse for EOSIO process and there will be no hole.

Note sure what to do here, seems it's not an easy task to cover correctly all cases. Ideally, in this "sync" mode, we should restart from scratch if we are unable to restore from snapshot, to play safe. To sure how to make that in the options directly.

A specific new option "sync"? When `merge-and-upload-directly` is used, it acts differently ensuring this constraints?

**Comment by maoueh** [comment]
Flagged as bug, but I feel we are missing some labels here, that would be more an enhancement/integrity thingy.

**Comment by maoueh** [comment]
Moreover, in this mode "syncing" and when a stop block is defined, we should probably trigger a snapshot like 200 blocks before the stop block.

The idea here is to more easily support phase 2 indexing where it needs to restart a little bit in the past to not miss any blocks. Otherwise phase 2 might restart with a snapshot taken far in past (15 minutes of syncing, not the end of the world also).

This might deserves a dedicated issue, and it's more an enhancement.

**Comment by sduchesneau** [comment]
Another option is to create one-block-files "after" the stop-block-num, so we do not discard anything.
This way is less of a surprise (why is it broken on restart, why do I need a snapshot restore, why am I missing blocks ?)

so if stop-block-num is 400, then we shutdown nodeos, and keep reading incoming blocks (401, 402, 403, 404...) and put them into one-block-files so that the merger can pick them up after restart.
