### ISSUE TITLE
Mindreader failed to start nodeos process after forced exit

### ISSUE THREAD

**Issue by theblockstalk** [dfuse-io/dfuse-eosio#32]
**Environment**
This runs dfuse using the docker image shown here https://github.com/dfuse-io/dfuse-eosio/issues/20
dfuse v0.1.0-beta2
eosio v2.0.3
eosio-cdt v1.7.0

**To reproduce**
- Run dfuseeos `dfuseeos start`
- Stop the process with Ctr+C
- Run dfuseeos `dfuseeos start`

**Expected**
Dfuse will start its services correctly after it was shut down

**Actual**
The following is displayed and the process exits with code 1
```
got err on get into (nodeos/monitoring.go:44) {"error": "http://:8888/v1/chain/get_info: Post \"http://:8888/v1/chain/get_info\": dial tcp :8888: connect: connection refused"}
notifying starting failure handler because process exited with non-success code within 10 seconds (superviser/superviser.go:167)
*********************************************************************************
* Mindreader failed to start nodeos process
* To see nodeos logs...
* DEBUG=\"github.com/dfuse-io/manageos.*\" dfuseeos start
*********************************************************************************

Make sure you have a dfuse instrumented 'nodeos' binary, follow instructions
at https://github.com/dfuse-io/dfuse-eosio/blob/develop/INSTALL.md
to find how to install it (cli/apps.go:208)
```

These are the last log lines:
```
{"level":"info","ts":1589905629.282772,"logger":"merger","caller":"merger@v0.0.0-20200422205004-c6c814e2004b/merger.go:311","msg":"retrieved list of files","seenblock_low_boundary":0,"bundle_lower_block":100,"seen_files_count":0,"too_old_files_count":0,"good_files_count":24}
{"level":"info","ts":1589905629.2829127,"logger":"merger","caller":"merger@v0.0.0-20200422205004-c6c814e2004b/merger.go:248","msg":"waiting for more files to complete bundle","bundle_lowerblock":100,"bundle_length":24,"bundle_upper_block_id":""}
{"level":"info","ts":1589905629.2831578,"logger":"search-router","caller":"router/router.go:91","msg":"routing active query","trace_id":"bbbf60e391efa894158414a7b3e71559","request":{"query":"receiver:eosio action:setabi notif:false","lowBlockNum":1,"highBlockUnbounded":true,"withReversible":true,"liveMarkerInterval":1},"head_delay_tolerance":0,"lib_delay_tolerance":0}
{"level":"info","ts":1589905629.2832675,"logger":"search-router","caller":"router/router.go:98","msg":"request received while router is not ready"}
{"level":"info","ts":1589905629.283731,"logger":"abicodec","caller":"abicodec/syncer.go:83","msg":"the search stream ended with error","error":"search stream terminated with error: rpc error: code = Unavailable desc = search is currently unavailable, try again shortly."}
{"level":"info","ts":1589905629.2837892,"logger":"abicodec","caller":"abicodec/syncer.go:86","msg":"waiting before startng ABI syncer"}
{"level":"info","ts":1589905629.295431,"logger":"blockmeta","caller":"blockmeta@v0.0.0-20200415145600-fef33cb242b8/server.go:114","msg":"cannot get stream's headinfo, retrying","error":"rpc error: code = Unavailable desc = not ready"}
{"level":"info","ts":1589905629.2972982,"logger":"relayer","caller":"relayer@v0.0.0-20200421150534-d4d76ebf6978/relayer.go:137","msg":"cannot get headinfo from backend","address":":13010","error":"rpc error: code = Unavailable desc = not ready"}
{"level":"info","ts":1589905629.2974823,"logger":"relayer","caller":"relayer@v0.0.0-20200421150534-d4d76ebf6978/relayer.go:98","msg":"cannot get head info mindreader, retrying forever","sources_addr":[":13010"]}
{"level":"info","ts":1589905629.3935611,"logger":"mindreader","caller":"superviser/superviser.go:165","msg":"command terminated","status":{"Cmd":"nodeos","PID":37,"Exit":254,"Error":{"Stderr":null},"StartTs":1589905623292244221,"StopTs":1589905629393467579,"Runtime":6.101223514,"Stdout":null,"Stderr":null}}
{"level":"warn","ts":1589905629.393886,"logger":"mindreader","caller":"superviser/superviser.go:167","msg":"notifying starting failure handler because process exited with non-success code within 10 seconds"}
{"level":"error","ts":1589905629.3939543,"logger":"dfuse","caller":"cli/apps.go:208","msg":"*********************************************************************************\n* Mindreader failed to start nodeos process\n* To see nodeos logs...\n* DEBUG=\\\"github.com/dfuse-io/manageos.*\\\" dfuseeos start\n*********************************************************************************\n\nMake sure you have a dfuse instrumented 'nodeos' binary, follow instructions\nat https://github.com/dfuse-io/dfuse-eosio/blob/develop/INSTALL.md\nto find how to install it."}
```

**Comment by theblockstalk** [comment]
I expect that the issue would be the same without running this through docker. I also suspect this is due to the non-graceful shutdown mechanisms of nodeos (if you shut down nodeos with Ctr+C you will need to replay the blockchain), though maybe you have fixed this.

**Comment by sduchesneau** [comment]
Hi @theblockstalk,

I can't reproduce this issue.
From source code (tag v0.1.0-beta2)
```
go install -v ./cmd/dfuseeos && yes | dfuseeos purge && yes | dfuseeos init && dfuseeos start
```

The Ctrl-C should output the following:
```
^CReceived termination signal, quitting
Goodbye
```

If the `-v` flag is used, it should look like:
```
(...)
(bstream) unsubscribed {"new_length": 1}
(bstream) unsubscribed {"new_length": 0}
(launcher) All apps terminated gracefully
(dfuse) Goodbye
```

I can't see how a simple ctrl-c would give you this issue, since the shutdown process is handled...

Unless:
1) you are piping the output of dfuseeos to another program ex: `grep`), then the "ctrl-c" would kill the "grep" program and make dfuseeos unable to cleanup.
2) you hit ctrl-c 3 times in a row (this results in a force kill)  -- this would show with a single verbose flag`-v` as the following:

```
^C(signals) Received termination signal... Ctrl+C multiple times to force kill {"signal": "interrupt"}
(dfuse) Received termination signal, quitting
^C(signals) Received termination signal twice, shutting down... {"signal": "interrupt"}
^C(signals) Received termination signal twice, shutting down... {"signal": "interrupt"}
^C(signals) Received termination signal 3 times: Forcing kill
```

Could you verify that you are not in one of those two conditions ?

**Comment by sduchesneau** [comment]
The implemented solution for a better "seemless" handling of that issue is deployed with version v0.1.0-beta3 (but it depends on a different nodeos version, the protocol for deep-mind patch has changed in the meantime)
Starting from v0.1.0-beta3, default flags will:
1) take a state snapshot on the mindreader every 15 minutes to default data location (--mindreader-auto-snapshot-period)  -- it keeps the last 5 snapshots and deletes the previous ones , according to --mindreader-number-of-snapshots-to-keep.
2) automatically restore the nodeos instance (from that )snapshot if it is broken on restart (it would handle the case that you are seeing here, restoring from latest previous snapshot)

I strongly suggest that you try that beta3 version with corresponding nodeos deep-mind patch.

Let me know if you have a chance to try this!

**Comment by maoueh** [comment]
@theblockstalk Something interesting to check. Yesterday I had mindreader exiting with error code 254 saying it had insufficient space to operate>

Something that might looking at. Not saying it was the case here.

**Comment by theblockstalk** [comment]
I have tried with dfuse v0.1.0-beta3 and confirm this does patch the solution by restoring from snapshop each time.

The problem itself was due to docker and how it managed exit codes being sent to dfuseeos process. In this case, I was piping dfuseeos output to a log file which caused the exit code to not be sent.

Using docker
In dockerfile this would work
`CMD dfuseeos start --data-dir /data`
but this would not and dfuse would not get a shutdown signal when docker exited
`CMD dfuseeos start --data-dir /data >> /data/dfuse.log 2>&1`

Using docker-compose I found the best thing to do was to use the following command override for the dfuse service
`command: ["dfuseeos", "start", "--data-dir", "/data"]`

Note in the above configuration I mapped a local directory to the /data dir in the docker container to have persistent storage for dfuseeos

You can close this ticket

**Comment by sduchesneau** [comment]
Glad to see that this is resolved!
interesting that a simple redirect would generate this behavior.

Good thing to note: the flag "--log-to-file" (bool) is true by default, and causes dfuseeos to always write the logs to {data-dir}/dfuse.log.json. This is not something that you will want in large-scale production, but always useful in local when something crashed and you had not set -v on command-line.
