### ISSUE TITLE
Check about indexing WAX `simpleassets` contract fields

### ISSUE THREAD

**Issue by maoueh** [dfuse-io/dfuse-eosio#39]
When we initially settled the indexed fields for the search, we added most `eosio.token` contract fields.

WAX NFT contract `simpleassets` is kind of the same now. It's been requested twice already, one time by some of developers around the official WAX and Syed from bloks.io.

The requested fields was `assetids` which seems to be a good idea to have indexed. We should probably check the contract more and check which other fields make sense to index there.

**Comment by jafri** [comment]
https://github.com/CryptoLions/SimpleAssets

**Comment by maoueh** [comment]
Here the relevant fields that could be added that are not actually caught by "pre-defined" indexed data fields:

```
assetid (id of the asset)
assetidc (id of container NFT)
assetids (vector of assetid, (id of the asset))
author (author of the asset)
category (assets category)
claimer (account claiming the NTT asset)
newowner (the future owner of the asset)
period (time in seconds that the asset will be lent for)
sym (fingible token symbol)
ftofferids (vector of ftofferid, ID of the FT offer)
```

I'm assuming we could do `assetid` (and the vectorize one), `assetidc`, `author`, `category`, `claimer`, `newowner`, `sym` and `ftofferid` (via the vectorize one).

No data point on the impact on the search indexes weight on disk yet though. Probably worth checking the different over a recent 1M chunk of blocks.

**Comment by sduchesneau** [comment]
done
