### ISSUE TITLE
eosq shows `Cannot query field "accountBalances" on type "Query".`

### ISSUE THREAD

**Issue by pkuphy** [dfuse-io/dfuse-eosio#4]
Thanks for your awesome work!

When I search for an account using `eosq`, for example `eosio`, the page shows `Cannot query field "accountBalances" on type "Query".`

**Comment by maoueh** [comment]
Congrats 🥳 First issue :)

So we did not add TokenMeta in the single binary but eosq was not updated to not use it.

This is indeed a bug.
