### ISSUE TITLE
eosq: load config in react dev server without devProxy

### ISSUE THREAD

**Issue by dliuproduction** [dfuse-io/dfuse-eosio#42]
We do not want to set up a devProxy server in go just for eosq, as it complicates the dev flow when not running dfuseeos. 
When `index.html` is not templated, we will use default config values from JS code, and load API Key from environment variable.

**Comment by maoueh** [comment]
@dliuproduction I want to avoid to have a dev proxy in fact. Let's discuss this together. I would like to only have to run the standard React dev server and not run an on-the-side proxy.

At the same time, it's less critical now that development flow for eosq is easier done using `dfuse for EOSIO`.

**Comment by maoueh** [comment]
We can discuss this when you want.

**Comment by dliuproduction** [comment]
done in a9470dc69a7f2026c5a8ad903de77065ebcec32a
