### ISSUE TITLE
--skip-checks not recognized as a valid flag

### ISSUE THREAD

**Issue by elmato** [dfuse-io/dfuse-eosio#50]
When running **dfuseeos** with --skip-checks it will show

```bash
Error: unknown flag: --skip-checks
Usage:
  dfuseeos start [flags]
...
```

~~the checks are skipped though~~

**version**
dfuseeos version 0.1.0-beta3-a45e062c6482a1c9765d5195cb451aed1a67e662

**Comment by maoueh** [comment]
Yeah that was a mistake, the flag was not global and was put only on `init` by mistake. It was fixed right after the release but not yet available: 66305a50a9fe1b4e4c7f3538658c0942fe6073fe.
