### ISSUE TITLE
Public key in transaction search is not correct

### ISSUE THREAD

**Issue by theblockstalk** [dfuse-io/dfuse-eosio#52]
The `pub_keys` value return in transaction queries `GET /v0/search/transactions` is not correct. We do not know what the keys shown are.

**Walkthrough of problem**
We bootstrap our blockchain with several transactions in [bootstrap-accounts.js](https://github.com/Conscious-Cities/eosio-react-app/blob/a738d786d716f4ce9994794aa715b06ea79758fd/back-end/test/bootstrap-accounts.js) where we specify the eosio.token transfer arguments, and the private key to sign with. e.g.
```
  await transferTokens("gov", "thenewfork", 3000, "", settings.eosio.accounts.yvo.pkey);
  await transferTokens("thenewfork", "jack", 600, "", settings.eosio.accounts.jack.pkey);
  await transferTokens("thenewfork", "kirsten", 600, "", settings.eosio.accounts.jack.pkey);
  await transferTokens("thenewfork", "matej", 600, "", settings.eosio.accounts.jack.pkey);
```
You can see the pub/priv keys in [settings.js](https://github.com/Conscious-Cities/eosio-react-app/blob/a738d786d716f4ce9994794aa715b06ea79758fd/back-end/settings.js)

We search for transactions in our React app using the `GET /v0/search/transactions` endpoint using the js SDK
```
const query = "(auth:"+state.accountName+" OR receiver:"+state.accountName+")"
let transactionRes = await eosio.dfuseClient.searchTransactions(query);
```
and then print out the public key
```
const publicKey = trx.pub_keys[0];
const blockNum = trx.execution_trace.action_traces[0].block_num;
let keyRes;
console.log(trx.execution_trace.action_traces[0].act.name, trx.execution_trace.action_traces[0].act.data, blockNum)
console.log(trx.pub_keys);
keyRes = await eosio.dfuseClient.stateKeyAccounts(publicKey, {block_num: blockNum});
console.log(keyRes); // Error thrown before here, key is not found
```
See line 93 and line 121 of [OrvView.js](https://github.com/Conscious-Cities/eosio-react-app/blob/c6c7f7a6922fcb03e18d2863aacf869ab4807d87/front-end/src/pages/OrgView.js). This shows the following output where we can see the public keys are not the ones corresponding to the signing key.
```
transfer Object { from: "gov", memo: "", quantity: "3000.00 EUR", to: "thenewfork" }
EOS7jdsDcTShSkZ6E32WXfrFk4aQ3ARAq1pVP71XFob8rj1dSgtJe
transfer Object { from: "thenewfork", memo: "", quantity: "600.00 EUR", to: "jack" }
EOS4vcU9MFRajXgNsxp9qcnFuCLcjKZ1EXebAgqFKv9pEXicYCdLX
transfer Object { from: "thenewfork", memo: "", quantity: "600.00 EUR", to: "kirsten" }
EOS81jUNCBWyW9gm8oeTArYp5PdJdCvg7vDYRkepJWjfSR5VWzyjt
transfer Object { from: "thenewfork", memo: "", quantity: "600.00 EUR", to: "matej" }
EOS7c7VXAdEAMeNcAqHvx6LtGcnGquYPGFGRPCaqoiTU4QLj7zLMC
```

We are running dfuse in docker:
https://github.com/Conscious-Cities/eosio-react-app/blob/a738d786d716f4ce9994794aa715b06ea79758fd/blockchain/Dockerfile-dfuse

**Comment by sduchesneau** [comment]
could you double check that you have the right chainID set under the flag --common-chain-id of the instance running trxdb-loader ?

**Comment by sduchesneau** [comment]
I confirm that the issue is definitely missing the `--common-chain-id` in trxdb-loader.

Bad news is: if you filled your database using trxdb-loader (with an empty or wrong chain-id), you will have to clear your data and start over with the `--common-chain-id=abcdef0123456` flag.

I'm working on the following changes to prevent this in the future:
1) setting the chain-id automatically when you use `dfuseeos init`
2) hard failing if trxdb-loader starts with an empty chain-id
3) (stretch goal...) detect if the given chain ID is wrong  (not sure where it would confirm; it could do a lookup on the API, but that's adding another dependency... )

**Comment by theblockstalk** [comment]
if we have `dfuseeos init` set up to run a production node, how can we know the chain id in advance so that we can run `defuseeos start` with the command?

**Comment by abourget** [comment]
heeeh! that's a good point.. ideally we'd fetch it dynamically from somewhere.. hmm, we'll think about it.

**Comment by theblockstalk** [comment]
I run `dfuseeos --common-chain-id df383d1cc33cbb9665538c604daac13706978566e17e5fd5f897eff68b88e1e4` which works fine because I do not modify the genesis block. This may not be the case for all dfuse nodes, it would be good if this were managed automatically for the nodeos node that dfuse connects to.
