### ISSUE TITLE
Data migration tooling

### ISSUE THREAD

**Issue by abourget** [dfuse-io/dfuse-eosio#54]
#### MVP
* [ ] Adapt eos-go Decoder to be "streamable" (i.e. use a Reader instead of reading everything in Memory)
* [ ] Read snapshot table and dump them into migration data format
* [ ] All resources limits on all accounts (export of data, injection code)
* [ ] All db secondary indexes (export of data, injection code)
* [x] Investigate `/v1/state/table` errors seen in eosq after import of data
* [x] Activate the right set of protocol features
* [x] _Export_, from flux, write to an established directory structure.
* [x] _Transfer `boot`_ from `eosc` into `dfuseeos` (through imports as much as possible)
* [x] _Import_: craft the `migration.inject` Op in the `boot` sequence
* [x] All db rows on all contracts
* [x] All permissions on all accounts (requires fluxdb refactoring + export of data, injection code)
* [x] All linked permissions on all accounts (export of data, injection code)
* [x] Typescript tool to manipulate exported data (https://github.com/dfuse-io/dfuseeos-migrator-client)
* [x] Read account permissions and dump them into migration data format
* [x] Read linked permissions and dump them into migration data format

#### Limbo (MVP or Nice To Have)
* [ ] Correctly set table payer quirks (logic to correctly make the good user pay for table creation on contracts)

#### Nice To have/Second Phase
* [ ] Performance testing of time to export data
* [ ] Performance testing & tweaks of time to import data (check with @abourget BIOS parameters, better packed actions into transaction, measurements, etc.)
* [ ] Documentation about the app and how user can use it
  * Document quirks about requirements (eosio key, eosio default contract, etc.)
* [ ] Exclude/Include accounts/contracts to export/import (to de define the expected behavior)
* [ ] Able to resume an import where we left off (find way to create "checkpoint", this is harder to implement as it's about reconciling expected state with desired state and execute the difference)

---

Here's a first draft of the flow:

Export from chain
* all accounts (whitelist, blacklist): snapshot at LIB at a given time, through fluxdb:
  * the account
    * its permission structs
    * its linked permissions
    * its cpu/net/ram associated resources
  * check whether its a contract: for a given block height.
    * whitelist/blacklist of contracts/tables combinations
    * list all tables (caught from the on-chain ABI, fetched since the "all accounts" snapshot)
    * all scopes
    * all rows

Outputs:
* large json file for accounts
* large json file(s) for tables
    `dir/{[ac]/[ou]/[acountName]}/tables/[tableName]/{[sc]/[pe]/[scopeName]}.json`
    example:
    `dir/dfu/se/dfuse44shine/tables/posts/eo/sc/eoscanadacom.json`
    `dir/{[ac]/[ou]/[acountName]}/codet.wasm`
    `dir/{[ac]/[ou]/[acountName]}/abi.json`
    `dir/{[ac]/[ou]/[acountName]}/account.json`
* large json of abi + code on current contract accounts

Processing:
* make a copy
* run some scripts for mutating them:
   * could pick up all updated contracts from a given directory (assuming contract/contract.wasm and contract/contract.abi)
     * everything that is left in the output dir, would be injected
     * anything left unchanged, will be passed on to the new chain
   * to alter `abi`, to reflect the migrated ones
   * to alter `code`
   * to alter table contents

Import phase:
* Mapping between how we want to apply `accounts` changes.
  * Series of transactions: `newaccount`
    * Set temporary key for `updateauth`, so we can apply any contract changes.
* For table data: code generation
  * For all contracts:
    * setabi to the NEW abi (after mutations)
    * setcode to `insert_row.wasm`
    * send transactions for ALL ROWS in the `mutated json` files, for the given contract
      * one-by-one, packed with the corresponding ABI
      * signer would need to be the same as the `payer` for the rows being inserted
        * OPT1: what about TABLE creation and billing? Who was the first creator in the original chain?
          * refinement:
            * get the payer for the TABLE
            * find a row that is from that payer
            * make it the first write.
        * OPT2: we write the first row, by altering its payer for the TABLE payer
          * we REWRITE that same first row, tweaking only its payer for the actualy payer of the row
          * continue on merrily
    * setcode to the NEW code (after mutations)

* Go through accounts again:
  * Remove the temporary authorization
  * Apply the `updateauth`, `linkauth`, `setalimits` (or `setacctram`, `setacctnet`, `setacctcpu`)

* update_row from Argentina needs ABI packing
  * https://github.com/EOSArgentina/Mallmann/blob/master/code/update_row/update_row.c

* eosio.setcode(update_row.wasm)
  targetcontract.whatever(binarypackeddatato write to the given row)
  eosio.setcode(original.wasm)

**Comment by abourget** [comment]
Flow:

```
dfuseeos boot --preset mainnet --initial-key=5K102938021983019283019283029CV


```
$ dfuseeos migrate export --fluxdb-grpc-addr --blacklist eidoseidos,powpowcoin --output ./migration-data/
Writing ./migration-data/bootseq.yaml
Writing ./migration-data/accounts/.../tables/...
Writing ./migration-data/accounts/.../tables/...
Done. Edit ./migration-data/bootseq.yaml to ensure.
```


dfuseeos migrate import ./migration-data

dfuseeos init --import ./migration-data
dfuseeos start import --import-from=./migration-data

dfuseeos migrate generate-boot ./migration-data

dfuseeos init bootseq --preset mainnet --output ./bootseq
dfuseeos boot init mainnet
dfuseeos boot

dfuseeos boot --preset migration
```

**Comment by abourget** [comment]
Improvements to deep-mind to fetch secondary indexes:
* protobuf model to be augmented to support `SecIndexOp`, representing mutations to secondary indexes.
* nodeos code needs to output data for secondary index mutations
* optimization + breaking change in behavior:
    * currently, we output a DbOp EACH TIME there's a call to `db_update_i64` or other state mutating functions.
    * instead, we'd want, at the _action_ level, to condense DbOps in order to keep only what was _actually_ changed when the action terminates. For example: 1) an INS + DEL for a given row results in a noop, thus there should be no DbOp, 2) a INS + UPD + UPD + UPD should result in a single INS, with the value of the last UPD.
    * ideally, once we have a struct that serves for deduplication at the action level (in apply_context? same place we `action_id++` ?), we can just print it once, one line instead of a lots of lines, hopefully saving space, and increasing speed (with less `printf` statements).
    * the implication of deduplication would mean we would NOT provide dbops for things that didn't change anymore, and we'd have les dbops, yet only the useful ones to express mutations that happened in the scope of an action.  Those who were relying on this would need to adapt, like send an inline action with the data they need if no state mutation exists, yet they wanted to track state data.

---

FluxDB to use protobufs as values (in the key/value store).
For a contract table data, the VALUE would be a protobuf that looks like:
```proto
message ContractRow {
    bytes value = 1;
    repeated SecIndexValue secondary_keys = 2;
}
message SecIndexValue {
  string index_name = 1;
  bytes key = 2;
}
```
That would be all the secondary keys pointing to the _primary key_ of the row in question.

**Comment by maoueh** [comment]
I think we can close this, feel free to re-open/re-work if you think we should still work/improve that feature.
