### ISSUE TITLE
for dfuseeos -log-format text to output anything you need to set environment

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#59]
for dfuseeos -log-format text to output anything you need to set environment. However environment is not documented anywhere

```
export INFO=mindreader
```

would expose mindreader info logging.  I suppose INFO takes a comma separated list of modules?

**Comment by sduchesneau** [comment]
Thanks for the  report, https://github.com/dfuse-io/dfuse-eosio/blob/develop/LOGGING.md should be complete now!
Also, I fixed a bug in manageos that prevented the nodeos logs from being categorized properly as info/warn/err (nodeos logs were always interepreted as debug...)

In your case, you may want to use the flags defined here: https://github.com/dfuse-io/dfuse-eosio/blob/develop/LOGGING.md#logs-produced-by-nodeos-mindreader-and-node-manager-dfuse-apps if you want to work with traditional nodeos log format.
