### ISSUE TITLE
eosq not accessible across the network

### ISSUE THREAD

**Issue by abourget** [dfuse-io/dfuse-eosio#6]
Seems to attach back to `localhost` all the time. Could use `window.location` or a relative path?

Reported by EOSUSA Michael on Telegram

**Comment by maoueh** [comment]
Yeah problem is the actual HTTP API endpoint is on :8080 while eosq runs on :8081. So a relative path cannot work.

We could do some transformation, take the hostname then append the 8081 port to it, but that would assume the deployment use the same hostname which could not be the case. And we would also need to send in the config the port to connect to.

My personal preference is to have the final value configurable, so the operator would inject the correct final deployment `hostname:port` where to hit the HTTP API. That would always be correct based on the deployment target. And when it's not defined, we assume `localhost:<PORT>`.

But indeed right now, it's hard-coded to `localhost:<PORT>` (See https://github.com/dfuse-io/dfuse-eosio/blob/develop/eosq/server.go#L114).

**Comment by abourget** [comment]
Rework of the ports (and intro of the `apiproxy` app) now allow you to expose only 1 port, which has all eosq and APIs blended together.
