### ISSUE TITLE
update dfuseeos to eosio 2.0.6

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#61]
block.one added some nice features in 2.0.6 (default thread priority changes).  It would be great to have a dfuseeos binary based on that 2.0.6

**Comment by maoueh** [comment]
Release done: https://github.com/dfuse-io/eos/releases/tag/v2.0.6-dm-12.0.

Homebrew not updated yet, but coming tonight or tomorrow.
