### ISSUE TITLE
implement new feature mindreader 'dumb-mode'

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#62]
This feature would have mindreader do nothing about managing snapshots or playing around with nodeos RPC or anything.  It would allow this usage:

```
nodeos | dfuse mindreader
```

Anyone using this mode would manage everything in nodeos outside of dfuse.

**Comment by abourget** [comment]
Interesting use case.. and that would just produce 100-blocks logs? Start the gRPC server to output logs too?

**Comment by matthewdarwin** [comment]
The idea is not not control nodeos. Everything else it normally does can stay.
nodeos output that is not for dfuse should be sent to stdout.

The idea is to allow someone (me) who already has infrastructure to deal with nodeos to not touch it as much as possible.

**Comment by sduchesneau** [comment]
Try it with `nodeos | dfuseeos start mindreader-stdin`, builds from 'develop' branch starting at b7babe8.
Pretty simple, so should be pretty solid.
