### ISSUE TITLE
PARTIAL_SYNC.md needs updating for EOS Nation snapshots instructions

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#64]
https://github.com/dfuse-io/dfuse-eosio/blob/develop/PARTIAL_SYNC.md

snapshots are now in zstd format (was previously bzip2)

**Comment by matthewdarwin** [comment]
There is also an apt package for zstd.

**Comment by maoueh** [comment]
Thanks added!
