### ISSUE TITLE
feature request: re-write the process name so it shows what is doing

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#71]
If I do a 'ps ax' on my server, I get a list that looks like this:
```
  923 ?        Ssl   13:20 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -vv start
 4211 ?        Ssl   30:29 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
 5334 ?        Ssl   29:49 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -vv start
10673 ?        Ssl    2:32 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
11607 ?        Ssl    0:53 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
18851 ?        Ssl    2:27 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
35921 ?        Ssl    2:15 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
59542 ?        Ssl   67:48 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
89784 ?        Ssl  725:04 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
89889 ?        Ssl    8:51 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -vv start
96737 ?        Ssl    4:59 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
97536 ?        Ssl    0:33 /usr/bin/dfuseeos -d /var/lib/dfuse -c /etc/dfuse/config.yml -v start
```
We're running a lot of dfuse binaries for lots of different purposes.  Just looking at the list here it's hard to tell what purpose is.

For example, it would be great if the "mindreader" process (with config below) would show mindreader in the 'ps' list.

```
start:
  args:
  - mindreader
  flags:
    config-file: ""
...
```

In our environment each process is running inside a (non-docker) container, so of course if I show the container context, then it is clear which is which.  But of course sometimes you're lazy.

**Comment by abourget** [comment]
Hmm.. Go multiplexes go routines on all the system threads transparently.. I'm not sure we could distinguish what does what at the `ps` level. Best thing would be to run each component in its own process, if you want a clear distinction.  Doing so should continue to work, because all "inter-app" communications happen through TCP sockets

**Comment by abourget** [comment]
If so, you could pass the app you're running as a parameter to `start`, like `dfuseeos start trxdb-loader`.. so you can view it in `ps ax`

**Comment by matthewdarwin** [comment]
We only have 1 process per binary I think.  Even if the binary is running multiple processes, the bunch of them could be listed.

I am not worried about thread names, that's a different thing altogether.

If I look at something like zabbix, they are quite detailed at the process level:

![image](https://user-images.githubusercontent.com/26171839/85077279-e5ad4900-b18f-11ea-96d4-bca2ddad5d23.png)

Would rather avoid changing the command line, cause then we need to do something special in systemd (which could be done with systemd override).  Ideally want all configuration in files.

**Comment by sduchesneau** [comment]
I'll check what we can do with https://github.com/erikdubbelboer/gspt we could maybe even normalize all parsed flags from config and add them to that virtual commandline

**Comment by sduchesneau** [comment]
It can't be done in Go (without using Cgo wrapper or "unsafe" package, which affects the build process in a very bad way, and even then, there are lots of ugly limitations on the length.)

ref: https://github.com/golang/go/issues/4053

Until it is supported in Go, I would go with Alex's recommendation that you pass the command-line argument to the commandline to see it.

Alternate crazy ideas:
* make a bunch of symlinks with different names (`relayer` as symlink to `dfuseeos` so you know what it's running by its name)
* always specify your config file as flag (`dfuseeos --config-file=/etc/dfuse/confs/relayer-mychain.yaml`) with a config name that tells you what's going on
* use a script that will launch the dfuseeos binary with all the flags as command arguments and use that script as the only config file.
