### ISSUE TITLE
ignore TERM signal when running in mindreader-stdin

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#72]
When running mindreader-stdin (reading from nodeos stdout), nodeos should exit first.  In case there is a TERM signal sent to both processes dfuseeos might exit first leaving the the chain in a dirty state.  This might occur during system shutdown for example.

To prevent this problem, if dfuseeos ignores TERM, then it the right thing will happen when nodeos exits and there is no more input to read and dfuseeos shuts down cleanly.

**Comment by sduchesneau** [comment]
Fixed in https://github.com/dfuse-io/dfuse-eosio/commit/440ce9dbd2b576e9453e8771cfe457efc32c22ff
