### ISSUE TITLE
Open source `tokenmeta`

### ISSUE THREAD

**Issue by abourget** [dfuse-io/dfuse-eosio#75]
dfuse currently runs `tokenmeta` (all popular tokens, all holders of a given token, all tokens of a given holder, sorted, etc..), which we hadn't open-sourced day one, to speed up the release process.

You can try the query here: https://mainnet.eos.dfuse.io/graphiql/?query=cXVlcnkgewogIHRva2VucyB7CiAgICBibG9ja1JlZiB7CiAgICAgIGlkCiAgICAgIG51bWJlcgogICAgfQogICAgcGFnZUluZm8gewogICAgICBzdGFydEN1cnNvcgogICAgICBlbmRDdXJzb3IKICAgIH0KICAgIGVkZ2VzIHsKICAgICAgY3Vyc29yCiAgICAgIG5vZGUgewogICAgICAgIHN5bWJvbAogICAgICAgIGNvbnRyYWN0CiAgICAgICAgaG9sZGVycwogICAgICAgIHRvdGFsU3VwcGx5CiAgICAgIH0KICAgIH0KICB9Cn0= (which lists tokens)

and here: https://mainnet.eos.dfuse.io/graphiql/?query=cXVlcnkoJGFjY291bnQ6IFN0cmluZyEsJGxpbWl0OglVaW50MzIsICRvcHRzOiBbQUNDT1VOVF9CQUxBTkNFX09QVElPTiFdKSB7CiAgYWNjb3VudEJhbGFuY2VzKGFjY291bnQ6ICRhY2NvdW50LGxpbWl0OiAkbGltaXQsIG9wdGlvbnM6ICRvcHRzKSB7CiAgICBibG9ja1JlZiB7CiAgICAgIGlkCiAgICAgIG51bWJlcgogICAgfQogICAgcGFnZUluZm8gewogICAgICBzdGFydEN1cnNvcgogICAgICBlbmRDdXJzb3IKICAgIH0KICAgIGVkZ2VzIHsKICAgICAgbm9kZSB7CiAgICAgICAgYWNjb3VudAogICAgICAgIGNvbnRyYWN0CiAgICAgICAgc3ltYm9sCiAgICAgICAgcHJlY2lzaW9uCiAgICAgICAgYmFsYW5jZQogICAgICB9CiAgICB9CiAgfQp9&variables=ewogICJhY2NvdW50IjogImVvc2NhbmFkYWNvbSIsCiAgIm9wdHMiOiBbIkVPU19JTkNMVURFX1NUQUtFRCJdLAogICJsaW1pdCI6IDAKfQ== (which retrieves balances for an account)

We don't want to have differences between the dfuse Community Edition and the hosted version, so we need to open-source it now.

It also has matured enough we might be able to make it beta instead of alpha, stress test it with the community, etc..

**Comment by sduchesneau** [comment]
done
