### ISSUE TITLE
Make Docker builds with tags on releases

### ISSUE THREAD

**Issue by sduchesneau** [dfuse-io/dfuse-eosio#77]
https://hub.docker.com/r/dfuse/dfuse-eosio is automatically pushed as latest
however, we have no github action on release (or goreleaser config ?) for pushing or promoting a docker image with the tag (ex: v0.1.0-beta4)

**Comment by maoueh** [comment]
Fixed by 623a92846a9d7b0dbc5111f91d01642a465b2a2e
