### ISSUE TITLE
When s3 storage is not responsive, dfuse doesn't issue any log messages

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#91]
If the s3 backend storage system is reacting slowly (or locked up and not sending any replies), then dfuse just sits and waits forever doing nothing (related to storage operations).  No error message are seen in logs.

Should dfuse have a timeout on all s3 operations and issue retry?

**Comment by sduchesneau** [comment]
This issue has been investigated and was caused by mindreader auto-merging being too unreliable. It,s been fixed since it now writes files locally and does proper retry for uploading.
