### ISSUE TITLE
mindreader-stdin needs to exit when asked, not waiting to upload all files to storage

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#93]
It appears (but I don't have any logs to show), that mindreader-stdin will, as part of its shudown process, upload all remaining files to s3 storage before exiting.

This is the only log I have:
```
2020-07-11T18:03:28.603Z (launcher) Still waiting for app "mindreader-stdin" ... 6s (launcher/launcher.go:271)
(repeated every few seconds)
```

If storage is non-responsive, then this blocks timely shutdown
If there are 1000s of pending files (because you are catching up old blocks), then this blocks timely shutdown

mindreader-stdin should shutdown when asked and not try to upload all the one-block files from the queue.

**Comment by matthewdarwin** [comment]
To be clear: mindreader is in "one block" mode for this scenario.

**Comment by sduchesneau** [comment]
Adding "WaitUploadCompleteOnShutdown" config option, which is a duration.

When shutting down, either `mindreader` or `mindreader-stdin` will only wait for upload completion for that amount of time (can be set to 0) before shutting down. Upon restart, the files lying around under `${DFUSE_DATA_DIR}/mindreader/work` are uploaded.

https://github.com/dfuse-io/node-manager/commit/09265ef6d3958360ca01b736fe023bdadcb655cd
