### ISSUE TITLE
Bug: unable to listen on ":13013": listen tcp :13013: bind: address already in use

### ISSUE THREAD

**Issue by NatPDeveloper** [dfuse-io/dfuse-eosio#98]
**Brief:** 

When running 2 instances of dfuseeos I see this error along with `13030`, `13018`, and `13010` I would say every 1/4 times I run my environment.

**Version:**

```
dfuseeos --version
dfuseeos version dev-
```

**Logs:**

[dfuse.log.txt](https://github.com/dfuse-io/dfuse-eosio/files/4921027/dfuse.log.txt)
[dfuse-liquidx.log.txt](https://github.com/dfuse-io/dfuse-eosio/files/4921028/dfuse-liquidx.log.txt)

**Steps to reproduce:**

You can try running your own version of these two files:

1. [02-a-eos-local-dfuse-eosio.js](https://pastebin.com/PGXXqZ4F)
2. [02-b-eos-local-dfuse-eosio.js](https://pastebin.com/rNrGfMuV)

These two files are a part of Zeus's unit testing / local environment framework.  If you would like an install link, feel free to hit me up and I can get you a link to this version of the code.

**Zeus Commands to reproduce:**

```
mkdir liquidx; cd liquidx; zeus box create; zeus unbox liquidx; cd zeus_boxes/dfuse; tsc; cd ../../; zeus test -c
```

**Error:**

`unable to listen on ":13013": listen tcp :13013: bind: address already in use`

**Stripped down commands to reproduce:**

First instance:

```
dfuseeos start -v \
    --search-archive-grpc-listen-addr ":13050" \
    --apiproxy-http-listen-addr ":8081" \
    --eosq-api-endpoint-url ":8081" \
    --dashboard-http-listen-addr ":8082" \
    --search-archive-http-listen-addr ":14016"
```

Second Instance:

```
dfuseeos start -v \
    --search-archive-grpc-listen-addr ":15051" \
    --apiproxy-http-listen-addr ":8083" \
    --eosq-api-endpoint-url ":8083" \
    --dashboard-http-listen-addr ":8084" \
    --search-archive-http-listen-addr ":15017" \
    --blockmeta-grpc-listen-addr ":15014" \
    --common-blockstream-addr ":15011" \
    --data-dir "./dfuse-liquidx-data" \
    --abicodec-grpc-listen-addr ":15013" \
    --dgraphql-abi-addr ":15013" \
    --common-search-addr ":15018" \
    --search-router-grpc-listen-addr ":15018" \
    --apiproxy-root-http-addr ":15030" \
    --eosq-http-listen-addr ":15030" \
    --apiproxy-dgraphql-http-addr ":15023" \
    --dgraphql-http-addr ":15023" \
    --apiproxy-eosws-http-addr  ":15026" \
    --eosws-http-listen-addr ":15026" \
    --common-blockmeta-addr ":15014" \
    --relayer-grpc-listen-addr ":15011" \
    --dashboard-eos-node-manager-api-addr ":15008" \
    --node-manager-http-listen-addr ":15008" \
    --dashboard-grpc-listen-addr ":15031" \
    --dgraphql-grpc-addr ":15024" \
    --eosws-fluxdb-addr ":15029" \
    --fluxdb-http-listen-addr ":15029" \
    --merger-grpc-listen-addr ":15012" \
    --relayer-merger-addr ":15012" \
    --mindreader-grpc-listen-addr ":15010" \
    --mindreader-manager-api-addr ":15009" \
    --search-forkresolver-grpc-listen-addr ":15027" \
    --search-forkresolver-http-listen-addr ":15028" \
    --search-indexer-grpc-listen-addr ":15021" \
    --search-indexer-http-listen-addr ":15022" \
    --search-live-grpc-listen-addr ":15117" \
    --trxdb-loader-http-listen-addr ":15020" \
    --apiproxy-nodeos-http-addr ":15888" \
    --eosws-nodeos-rpc-addr ":15888" \
    --node-manager-nodeos-api-addr ":15888" \
    --mindreader-nodeos-api-addr ":15889" \
    --blockmeta-eos-api-extra-addr ":15889" \
    --blockmeta-eos-api-upstream-addr ":15888" \
    --node-manager-config-dir "./producer-liquidx" \
    --mindreader-config-dir "./mindreader-liquidx" \
    --relayer-init-time 10m0s
```

**Comment by abourget** [comment]
For which port is 13013 the default value? Is it possible it is not specified here?

I sometimes feel it'd be useful to have a default port value shifter, like `--common-default-ports-offset`.. and it would simply add to the default port values. Not sure it would be easily done with cobra, could check.

**Comment by NatPDeveloper** [comment]
For the first instance, I'm running the defaults:

```
dfuseeos start -h | grep 13013
      --abicodec-grpc-listen-addr string                      Address to listen for incoming gRPC requests (default ":13013")
      --dgraphql-abi-addr string                              Base URL for abicodec service (default ":13013")
```

For the second instance:

```
    --abicodec-grpc-listen-addr ":15013" \
    --dgraphql-abi-addr ":15013" \
```

**Comment by abourget** [comment]
Hmm.. from the code's perspective, it seems all good. I don't see anything listening on `:13013` by default, and `dgraphql-abi-addr` is an outgoing address, for it to connect to `localhost:13013` when it needs to contact `abicodec`.

I know you probably have chacked already, just wondering if it's possible an older `dfuseeos` is still running, when you launch that one?

**Comment by NatPDeveloper** [comment]
This is a good point to check as I did accidentally run the older version once.  It's hard to tell which version I'm on as the dev branch simply reports:

```
dfuseeos --version
dfuseeos version 0.1.0-beta3-a45e062c6482a1c9765d5195cb451aed1a67e662
```

And it looks like somehow I'm on beta3 and not dev.  Recompiling and seeing if I can reproduce without killing the ports prior.

**Comment by NatPDeveloper** [comment]
Updated version (included in post) and recreated logs (first log should contain issue).

**Comment by NatPDeveloper** [comment]
Well after updating I'm not able to reproduce.  The first time it did it, but that could have been related to how the previous version shutdown. Closing until I can reproduce.

**Comment by NatPDeveloper** [comment]
Re opening as seeing error again on latest version.  Deleted previous binary to be sure new one is updated.  Would help if dev branch came with versioning.

```
################################################################
Fatal error in app tokenmeta:

unable to listen on ":14001": listen tcp :14001: bind: address already in use
################################################################
```

Full log is 1.2GB ...

```
du -sh dfuse-liquidx-data/dfuse.log.json 
1.2G    dfuse-liquidx-data/dfuse.log.json
```

Tailed last 5000 lines attached:

[op.txt](https://github.com/dfuse-io/dfuse-eosio/files/4944022/op.txt)

Dfuse-eos output attached

[dfuse-dfuseos-output.log.txt](https://github.com/dfuse-io/dfuse-eosio/files/4944019/dfuse-dfuseos-output.log.txt)

**Comment by NatPDeveloper** [comment]
Looked at the changelog, were some flags that needed to be added. 

https://github.com/dfuse-io/dfuse-eosio/blob/develop/CHANGELOG.md
