### ISSUE TITLE
Mindreader should write temporary files locally while `mindreader-merge-and-store-directly: true`

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#99]
When mindreader is in `mindreader-merge-and-store-directly: true` mode, it writes files directly to s3 storage.  This has two issues:

1) when replaying blocks on a network with very small transactions, you can easily replay 10 merged-blocks (1000 blockchain blocks) in 1 second.  Storage may not be able to handle this incoming rate, so storage slows down the entire replay.

2) If the storage server is being unreliable for some reason, mindreader will do all the processing but end up not uploading the blocks to storage and they are lost.  

In both cases, better to write the blocks locally and then they could at least be manually uploaded.

**Comment by abourget** [comment]
We'll be working on a write-to-disk merge_archiver, it's a good idea to keep many of those files on disk. We'll take note

**Comment by abourget** [comment]
See https://github.com/dfuse-io/node-manager/issues/9
